# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: deploy lambda from local source code

on:
  push:
    branches:
      - main
    paths:
      - "backend/**"

env:
  lambda_name : GetPageVisitsLambda

jobs:
  deploy-lambda:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Configure AWS credential
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: zip lambda code
        run: zip -j deploy.zip backend/src/get_page_visits.py
      - name: update lambda
        run: |
          aws lambda update-function-code 
          --function-name  $lambda_name
          --zip-file fileb://deploy.zip

